### PR TITLE
Bumps ws to latest version and replaces babel for esm

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Since this doesn't include any tests I used the `example/simple.js` to verify it still works with the new version.

I've also replaced babel with esm in this meaning no more compiling just to add import/export support.

For now to use this run either of these and you'll be good to go.
```shell
$ npm install https://github.com/OmgImAlexis/express-ws
$ yarn add https://github.com/OmgImAlexis/express-ws
```

Replaces https://github.com/HenningM/express-ws/pull/95
Closes https://github.com/HenningM/express-ws/issues/90

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
Replaces https://github.com/HenningM/express-ws/pull/95

**Comment by OmgImAlexis** [comment]
@HenningM any chance this could be reviewed soon?

**Comment by OmgImAlexis** [comment]
@HenningM sorry for the constantly pinging but this is something that's affecting me everyday at work.

As it seems you're still busy I'd like to offer taking over maintaining this for you until you're free enough to come back.

**Comment by HenningM** [comment]
Hi @OmgImAlexis,

First of all: my sincere apologies for not getting to this PR sooner. Unfortunately I haven't been able to give this project the attention it deserves lately. I'll do my best to improve the situation in the coming weeks and months, but I'm also open to the idea of inviting someone else to (co-)maintain this.

The changes in the PR look good to me at first glance, but I'll need to have a closer look before I can merge & release this. I'll get back to you tomorrow evening (UTC).

**Comment by OmgImAlexis** [comment]
No worries. Thanks for getting back to me.

**Comment by OmgImAlexis** [comment]
@HenningM would you mind publishing a new version to npm?
The last published version is 5 months old.

**Comment by safareli** [comment]
@HenningM  can you please publish new version on npm?

**Pull request merged**
