### PR TITLE
Rewrite to add Express Router support, update documentation

### PR DESCRIPTION
**Pull request by joepie91**
As I noted in #8, I've rewritten this module to support Express Routers (and any kind of custom, compatible router) as well. Notable changes:

* Rewritten using ES6 and Babel.
* Now supports Express Routers.
* Reverted the `.websocket` location change from #17 - it's now suffixed to the route again, to allow for Routers to propagate the request normally. However, it now ensures that it doesn't interfere with the query by splitting up the URL first, thereby leaving #17 fixed.
* Supports custom routers by explicitly calling an `applyTo` method on them (see the documentation).
* Introduces a __potentially breaking__ change, by modifying the `express.Router` prototype. This warrants a major version bump (ie. to 2.0.0).
* Added option to turn off this new Router-modifying behaviour.
* Updated and improved documentation.
* Also added many more comments in the code itself, about why things are done a certain way - it took me a long time to figure this out for the original code, as `express-ws` (necessarily) does some strange things to make it work.

I've kept the Babel build process to a single NPM script (`npm run build`) to avoid introducing a build stack. You might want to change this, of course.

Notes:

* All examples in `examples/` still work fine.
* Still won't support RegExp literals (like the old version), but the [parameter string syntax](https://stackoverflow.com/a/13665354/1332715) should work fine. I'm not convinced that it can be made to work with RegExp literals, but I've not looked too deeply into it.

### CODE REVIEW

**Comment by HenningM** [comment]
Hi!

Thanks a lot for this contribution! Implementing this feature has been on my agenda for a long time, but I never found time to actually do it. On the surface your changes seem reasonable. I'll have a closer later today.

BTW: I'm really sorry that you had to decipher the already existing code without having any help in the form of comments :wink:

**Comment by joepie91** [comment]
No worries!

After rewrting it,  I realized that your approach of sending a wrapped request to a 'fake' internal route was basically the most reasonable way to implement this anyway - it seems that integrating WebSockets into Express is just an inherently messy thing to do, so that's going to result in strange code no matter what you do. Hence also the addition of lots of comments to the code, so that hopefully it'll be a bit more obvious to the next reader :)

**Comment by HenningM** [comment]
Hi again,

I've created a new 2.0 branch and merged your changes in there. I've also added a few modifications on top of yours. If you have a few moments to spare it would be nice if you could have a look and tell me if I broke any of the functionality you added. When everything is OK from both our sides I'll merge the 2.0 branch into master and publish a release candidate to NPM. 1.0 will be maintaned in a new branch based on the current master.

The changes I've made:
* Removed lib/ from git repository and instead added a prepublish script which runs babel and generates this directory
* Moved the changelog to a separate file
* Added an eslint config & npm 'lint' script
* Rewrote all JS to airbnb styleguide compliant and idiomatic ES6
* I've obviously also added you as a contributor in the package.json file

**Comment by joepie91** [comment]
Alright, so I've left a lot of comments in [this commit](https://github.com/HenningM/express-ws/commit/257a9e8dca24c0a1fd895ebdf3fb98ce4fbcffa9#diff-1fdf421c05c1140f6d71444ea2b27638R10). The `standard` style guide really isn't very good to begin with (it just defines arbitrary rules without providing a rationale), and it doesn't really recognize the fact that readability is largely context-dependent.

Following from that, a few other concerns:

* Using spaces for indentation is not generally a good idea. Tabs allow the reader to configure the display width to whatever is easiest for them to understand, whereas spaces do not. In that sense, tabs contribute a lot to readability.
* I'm unsure of the default configuration of `eslint`, but I'd recommend turning off any style-related rules, and only enabling rules that recognize common mistakes. Software really cannot tell what is readable to a human.

Mind also that arrow functions are not functionally equivalent to regular functions, and that checking for a falsey value is something very different from checking whether a value is set - I've also pointed out some of these cases in the comments in the commit.

**Comment by HenningM** [comment]
Thanks a lot for all the comments! I definitely agree with a lot of your points, and I have to admit that some of my changes were very unfortunate. I'll go through each comment later today and fix things up.

I appreciate your opinion about tabs vs spaces, and personally I don't disagree. But within the JS community in general and Node.js in particular the norm is to use two spaces for indentation. I'm not saying that the majority is always right. That's very rarely the case, and might not be true here either. But I still want the majority to feel comfortable with and recognize the formatting of the code.

Regarding your concerns about eslint & style guides I have to say that I agree that there are no end-all and be-all JS style guides at this point. This is obviously a real shame, because I _do_ believe in enforcing consistent formatting. That's why I added both the editorconfig file and the eslint configuration. I ended up going for [airbnb](https://github.com/airbnb/javascript)'s guide, since that at least provides some rationale for its rules. If you have any other suggestions here I'm open for suggestions.

Your point regarding arrow functions is a very good one. I went completely overboard with those. Some of them, if not all, will be changed back into regular functions. Same goes for falsey value checking. Some very rushed changes there as well.

**Comment by joepie91** [comment]
> I appreciate your opinion about tabs vs spaces, and personally I don't disagree. But within the JS community in general and Node.js in particular the norm is to use two spaces for indentation. I'm not saying that the majority is always right. That's very rarely the case, and might not be true here either. But I still want the majority to feel comfortable with and recognize the formatting of the code.

I wouldn't worry about indentation being "consistent within the community". Every major code editor and IDE out there is capable of automatically adjusting the indentation to the dominant style in a codebase/file, and most of them do so out of the box. If one sets their (global) tab width to 2, then to them, it's going to work precisely the same as 2-space indentation would.

I've had many people complain about my use of tabs in the past (in particular around Python), but precisely zero of those complaints had been of a technical nature - it has *always* been an argument of consistency for the sake of consistency, which helps nobody. Readability is much more important than consistency, and you can't programmatically (or rule-wise) enforce readability.

> I ended up going for airbnb's guide, since that at least provides some rationale for its rules. If you have any better suggestions here I'll consider them.

I generally recommend against style guides entirely. Readability is *heavily* context-dependent, and style guides really aren't a good technical solution - their popularity comes from the fact that it's a *cheap* solution to enforce a 'minimum standard' across a poorly-disciplined team of developers. It's an economic decision that doesn't really make much sense outside of economics.

A much better approach is to just optimize for readability (which will often involve consistency, but not always), and 'judge' pull requests on that the same way they are judged on a style guide now.

**Comment by imvanzen** [comment]
Hello guys!
Have anything changed from July with this PR? Being honest, this would be my blessing right now.
I have exact same need as reporter of this Issue [#8](https://github.com/HenningM/express-ws/issues/8). I appreciate your help.
Cheers!

**Comment by joepie91** [comment]
@imvanzen For what it's worth, I've just published my original fork to NPM as a scoped package: [`@joepie91/express-ws`](https://www.npmjs.com/package/@joepie91/express-ws). I'll probably deprecate that package once this PR gets merged, but it can at least serve as an interim solution.

**Comment by imvanzen** [comment]
Thank you @joepie91 for instant reaction!
Until the original package will be published this is enough for me.

**Comment by HenningM** [comment]
Hi @joepie91 & @imvanzen,

I'm sorry that this has been stuck for a while. This PR adds a highly desired feature to the library, so I should have published a version containing this feature a long time ago. Once again: thanks a lot for the contribution, @joepie91. I'll publish a new version to npm later today or tomorrow.

**Pull request merged**
